[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # WordPress API Configuration
  WORDPRESS_API_URL = "http://dodgerblue-rail-758925.hostingersite.com/wp-json"
  WORDPRESS_CUSTOM_API_URL = "http://dodgerblue-rail-758925.hostingersite.com/wp-json/renovalink/v1"
  WP_MEDIA_URL = "http://dodgerblue-rail-758925.hostingersite.com/wp-content/uploads"
  
  # API Cache Settings
  API_CACHE_TTL = "300"
  
  # Production Settings
  NODE_ENV = "production"
  
  # Email / Secrets (DO NOT commit real credentials)
  # Set these in Netlify UI (Site > Settings > Environment variables)
  # GMAIL_USER = "${GMAIL_USER}"          # <-- configure in dashboard
  # GMAIL_APP_PASSWORD = "${GMAIL_APP_PASSWORD}"  # <-- configure in dashboard
  # COMPANY_EMAIL = "${COMPANY_EMAIL}"    # <-- configure in dashboard

# Headers para optimización de assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Forms para el formulario de contacto
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# SSR redirection is handled by @astrojs/netlify adapter

# Prevent stale HTML caching (ensure users always get the latest deploy HTML)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Strengthen caching for built asset directory (if using /assets/ for any static outputs)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"